name: Bug report
description: Report a bug
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill up this bug report!

        In order to help us debugging, please provide as much information as you can.
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
  - type: textarea
    id: current-behavior
    attributes:
      label: What is the current behavior?
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots or video captures to help explain the problem.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information that could help debug the problem.
